### ISSUE TITLE
Errors after OTP is entered

### ISSUE THREAD

**Issue by maidenform** [zerotypic/wasg-register#1]
Was not able to run it as ./wasg-register but was able to run it as python /wasg-register

Received the following after the OTP was entered.

Traceback (most recent call last):
  File "wasg-register.py", line 310, in <module>
    if __name__ == "__main__": sys.exit(main())
  File "wasg-register.py", line 271, in main
    enc_userid = enc_userid_hex.decode("hex")
AttributeError: 'str' object has no attribute 'decode'

Any idea what i need to do? (Would like to add that I think the Wireless@SGx provider around where i tried is provided by M1)

**Comment by zerotypic** [comment]
What version of Python are you using? I suspect Python 3, which I just realised doesn't have a decode() function on str objects. I've not tested the code out on Python 3 yet, and will probably need to change several things to make it work. In the meantime, you can probably get it working by running it in Python 2.
