### ISSUE TITLE
Adding NetworkManager Config

### ISSUE THREAD

**Issue by chuanhao01** [zerotypic/wasg-register#16]
Hi @zerotypic,

I want to preface this issue by saying thanks for the work you and the other contributors have done for this project. I have followed along and was able to use the script to generate a working profile that I am using right now :).

However, I realized that there were no instructions, after generating a profile, to use `NetworkManager` to connect to the network using the generated profile.

Therefore I created this issue to ask if it was okay to add a section in the `README.md` for this, similar to the tips for `wpa_supplicant.conf`.

I already made some changes for how it could look like [here](https://github.com/chuanhao01/wasg-register/tree/adding-network-manager-config)

**Comment by zerotypic** [comment]
Hi, looks fine to me, just submit a pull request for the README and I'll merge it.
