### ISSUE TITLE
Support non-NRIC registration

### ISSUE THREAD

**Issue by zerotypic** [zerotypic/wasg-register#2]
Currently, a valid NRIC number is required for registration using this wasg-register. However, the official Wireless@SG apps can register without needing an NRIC; for example the Android app just needs a date of birth. This might involve an alternative API. Figure out how it works and implement it in wasg-register.

**Comment by zerotypic** [comment]
Implemented as of commit c79028b.

**Comment by jchintk** [comment]
Hi 

I'm unable to connect to Wireless@SGx referring on the below exact same question:-

https://gitmemory.com/issue/zerotypic/wasg-register/7/701099727

How did it worked?

Thanks in advance
JTK
