### ISSUE TITLE
wasg-register issue

### ISSUE THREAD

**Issue by harishpillay** [zerotypic/wasg-register#27]
wasg-register has been working well so far on all of my Fedora systems. I just updated to Fedora 39 and tried to set up on a new laptop access to wireless@sg.

`% python3 wasg-register.py -r 65xxxxxxxx ddmmyyyy

OTP will be sent to mobile phone number 65xxxxxxxx

Enter OTP to continue: 576889

Traceback (most recent call last):
  File "/home/harish/wasg-register/wasg-register.py", line 396, in <module>
    sys.exit(main())
                 ^^^^^^
  File "/home/harish/wasg-register/wasg-register.py", line 366, in main
    if decrypt(key, r["nonce"], r["tag_userid"], r["enc_userid"]) == r["userid"]:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/harish/wasg-register/wasg-register.py", line 217, in decrypt
   aes = AES.new(key, AES.MODE_CCM, nonce)
                                       ^^^^^^^^^^^^
AttributeError: module 'Crypto.Cipher.AES' has no attribute 'MODE_CCM'. Did you mean: 'MODE_CBC'?
`

**Comment by zerotypic** [comment]
This is probably because you need to use the PyCryptodome library. Can you check if it is installed?

**Comment by harishpillay** [comment]
> This is probably because you need to use the PyCryptodome library. Can you check if it is installed?

seems to be:
`% pip install pycryptodomex

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pycryptodomex in /usr/lib64/python3.12/site-packages (3.19.0)
`

**Comment by zerotypic** [comment]
Ah, seems like pycryptodomex puts its stuff inside the "Cryptodome" package, and not the "Crypto" package.

Try changing this line:
https://github.com/zerotypic/wasg-register/blob/e2ebe3a7134da7c6509c6c1739eb9594ca8eff6c/wasg-register.py#L16

to `from Cryptodome.Cipher import AES`, and see if it works.

If it does, I can probably add a guard to handle this particular situation.

**Comment by harishpillay** [comment]
> Ah, seems like pycryptodomex puts its stuff inside the "Cryptodome" package, and not the "Crypto" package.
> 
> Try changing this line:
> 
> https://github.com/zerotypic/wasg-register/blob/e2ebe3a7134da7c6509c6c1739eb9594ca8eff6c/wasg-register.py#L16
> 
> to `from Cryptodome.Cipher import AES`, and see if it works.
> 
> If it does, I can probably add a guard to handle this particular situation.

I just got to a location that I needed to access Wireless@SGx on my laptop (Jurong East Regional LIbrary). And yes, that was the fix that was needed.

I did also encounter a urllib3.packages.six error:

```
python3 wasg-register.py 65nnnnnnnn ddmmyyyy
Traceback (most recent call last):
  File "/home/harish/wasg-register/wasg-register.py", line 11, in <module>
    import requests
  File "/home/harish/.local/lib/python3.12/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/home/harish/.local/lib/python3.12/site-packages/urllib3/__init__.py", line 7, in <module>
    from .connectionpool import HTTPConnectionPool, HTTPSConnectionPool, connection_from_url
  File "/home/harish/.local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/home/harish/.local/lib/python3.12/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import IncompleteRead as httplib_IncompleteRead
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'
```

This was before the change that you proposed.

I had to ```pip uninstall urllib3``` and ```pip install urllib3``` and then with the change you've proposed, it went well.

Thanks for all that you've done.
