### ISSUE TITLE
Generate a QR code to scan to add wifi on android?

### ISSUE THREAD

**Issue by ackerleytng** [zerotypic/wasg-register#29]
I was thinking to perhaps generate a scannable QR code to add wifi on android, and iPhone?

From a brief search online, the format seems to be some variation of `WIFI:T:WPA2-EAP;S:Wireless@SGx;E:PEAP;PH:MS-CHAPv2;AI:<anonymous identity>;I:<identity>;P:<password>;;`

And we could either use some python library or `qrencode`, like 

```
qrencode --type=ansiutf8 STRING_FROM_ABOVE
```

I couldn't figure out the anonymous identity, identity and password though. Has anyone else managed to use the output of this script on the phone?

Thank you so much for this script btw :)

**Comment by zerotypic** [comment]
That's a pretty good idea.. we can probably have a flag that outputs the string, which users can just pipe to `qrencode` to generate the QR code. I don't have the time to go figure out the exact format needed though; I know how it works for WPA2 personal creds, but not for EAP. Maybe somebody can work on this and I'll merge it in.

**Comment by harishpillay** [comment]
On my laptop running Fedora 39 (should work with other distros as well), the following command, ```nmcli dev wifi show-password``` (which I've aliased in .bashrc as ```alias wifi="nmcli dev wifi show-password"```). I type "wifi" at the prompt and QR code thus generated can be scanned by the phone and get connected. I need to check if this QR code would work on a wasg setting. Perhaps my next visit to the library.

**Comment by ackerleytng** [comment]
@harishpillay if you scan the QR code shown from `nmcli dev wifi show-password` (and remove anything sensitive), what is encoded in the QR code? I don't use nmcli so if you could share what's encoded it'll save me some setup :)

@zerotypic piping to qrencode is a great idea! More unix-y

**Comment by harishpillay** [comment]
What's encoded in the QR code is the SSID, type of encryption and password. Nothing more. ```nmcli``` should be available in all distros.

**Comment by ackerleytng** [comment]
Looks like if [this](https://cs.android.com/android/platform/superproject/main/+/main:packages/apps/Settings/src/com/android/settings/wifi/dpp/WifiQrCode.java;l=50;drc=2078bffca5927b7f65e1b8005b919b37848e2b59;bpv=1;bpt=1?q=%22WIFI:%22) is being used to parse the string encoded in the QR code, we're out of luck since it's not even parsing the EAP method or phase 2 authentication, etc.

**Comment by zerotypic** [comment]
> Looks like if [this](https://cs.android.com/android/platform/superproject/main/+/main:packages/apps/Settings/src/com/android/settings/wifi/dpp/WifiQrCode.java;l=50;drc=2078bffca5927b7f65e1b8005b919b37848e2b59;bpv=1;bpt=1?q=%22WIFI:%22) is being used to parse the string encoded in the QR code, we're out of luck since it's not even parsing the EAP method or phase 2 authentication, etc.

Looks like that's most likely the case, too bad! I'll close this issue then.
