### ISSUE TITLE
Received error message from server: API incorrect

### ISSUE THREAD

**Issue by weichiehlim** [zerotypic/wasg-register#3]
Hi, I get an error when running the script ...

# ./wasg-register.py -v 65xxxxxxxx Sxxxxxxxx
Server response reports an error, resultcode = 1101
Received error message from server: API incorrect
Server responded with error message: API incorrect

**Comment by zerotypic** [comment]
I'm getting the same error, they probably changed their API. I don't have time to RE the protocol again right now unfortunately... might only be able to sometime in November.

**Comment by JiunHong** [comment]
Would be great if we can get the new API. I tried using r1b and stuff but without being able to decompile, it'll be difficult..

**Comment by doodoo-aihc** [comment]
They have changed their API to adhere to the recent PDPA law to use date of birth instead of NRIC. I have reverse engineered most of the new API changes and I'll send in a pull request in a few days time as I'm having some trouble decrypting the encrypted user id & password.

**Comment by zerotypic** [comment]
Thanks! Let me know if you need any help with the decryption. I'll try to make my way to a Wireless@SG hotspot sometime this week so I can test things out; haven't been able to work on this for the past few months.

**Comment by zerotypic** [comment]
@IkaEren Did you push the latest copy of your code to your fork? I was taking a look at it and it seems incomplete.

**Comment by doodoo-aihc** [comment]
Hello @zerotypic, the code in the fork is unfinished because the decryption code has some problems and I didn't manage to fixed it. The API endpoint for Singtel should be correct and I was able to get the OTP to my phone number. Instead I created a .NET core console application to get the decrypted password lolx. 

Here's the project github - https://github.com/IkaEren/AESDecrypt

**Comment by zerotypic** [comment]
Ok thanks! I've gotten the new API calls worked out, going to look at the decryption now.

**Comment by zerotypic** [comment]
Ok, I've updated the code to work with the new API, including decryption. Do try it out! While I managed to decrypt the password, I'm not nearby a Wireless@SG hotspot right now so I can't verify it really works; if anybody manages to do that please let me know and I'll close this issue.

**Comment by zerotypic** [comment]
Alright, I've managed to successfully use the retrieved creds (at SGH of all places) so I'm going to close this.
