### ISSUE TITLE
API issues

### ISSUE THREAD

**Issue by harishpillay** [zerotypic/wasg-register#4]
I am trying this out and look like the've indeed changed the API. I am at the Jurong Regional Library and it is covered by M1. 

./wasg-register.py 65NNNNNNNN SNNNNNNNX -I myrepublic
Warning: Unexpected server response, key 'api' is 'core', not 'create_user_r1a'.
Warning: Unexpected server response, key 'version' is '1.2', not '2.1'.
Traceback (most recent call last):
  File "./wasg-register.py", line 310, in <module>
    if __name__ == "__main__": sys.exit(main())
  File "./wasg-register.py", line 240, in main
    args.transid)
  File "./wasg-register.py", line 91, in request_registration
    _validate(resp["body"], "success_code", fatal=True)
  File "./wasg-register.py", line 53, in _validate
    err("Warning: Server response did not contain key '%s'." % (key,))
  File "./wasg-register.py", line 50, in _raise
    def _raise(m): raise MalformedResponseExn(m)
__main__.MalformedResponseExn: Warning: Server response did not contain key 'success_code'.

Seems that, despite of me reaching out to IMDA, they've decided to just go break this solution. 

I will update once I get another meeting with the IMDA folks on this.

**Comment by J370** [comment]
Indeed, it just so happens that I am also at Jurong Regional Library facing the same issues.

**Comment by zerotypic** [comment]
I've updated the code to work with the latest API. While I've managed to get a set of credentials, I've not had the chance to verify they actually work yet as I'm not near a Wireless@SG hotspot. If any of you do get it to work, please let me know and I'll close this issue. Thanks!

**Comment by zerotypic** [comment]
Tested successfully, closing.
