### ISSUE TITLE
Not working in Python 3

### ISSUE THREAD

**Issue by harishpillay** [zerotypic/wasg-register#5]
I just ran the latest version and this is the output:

> [harish@gillman wasg-register]$ ./wasg-register.py MOBILE DOB
> Warning: Unexpected server response, key 'version' is '2.4', not '2.3'.
> OTP will be sent to mobile phone number MOBILE
> Enter OTP to continue: 297433
> Traceback (most recent call last):
>   File "./wasg-register.py", line 375, in <module>
>     sys.exit(main())
>   File "./wasg-register.py", line 332, in main
>     retrieve_mode=args.retrieve_mode)
>   File "./wasg-register.py", line 181, in validate_otp
>     "enc_userid" : str(resp["body"]["enc_userid"].decode("hex")),
> AttributeError: 'str' object has no attribute 'decode'
> [harish@gillman wasg-register]$ 

Not sure what I am missing.

**Comment by zerotypic** [comment]
You're probably running Python 3. I really need to get the code ported...

In the meantime you can probably get it to work by explicitly running it using the Python 2 interpreter. Also, the warning message is harmless; different ISPs reply with different versions for some reason.

**Comment by harishpillay** [comment]
Yes, I am on Python 3. I think it is critical to have it on Python 3. Python 2 sunsetted on Jan 1, 2020.

**Comment by zerotypic** [comment]
I know.. I've been busy porting code to Python 3 the past week. Technical debt... :'(

**Comment by harishpillay** [comment]
I understand. I can take a peek at the code and try my hand at it.
