### ISSUE TITLE
Not connecting to Wireless@SGx after adding credentials

### ISSUE THREAD

**Issue by jchintk** [zerotypic/wasg-register#8]
Hi zerotypic,

I have got into the same issue as been reported earlier as in the link below but no solution was found there :-

https://gitmemory.com/issue/zerotypic/wasg-register/7/701099727

How did it worked ?

Thanks,

**Comment by jchintk** [comment]
I have successfully retrieved a username and password pair, 
The network config is PEAP version automatic, anonymous identity blank, MSCHAPv2.
Same as https://github.com/zerotypic/wasg-register/issues/7
Any idea why not working?

**Comment by zerotypic** [comment]
I'm not sure, but it's likely a configuration issue. Maybe see if you can get the credentials working successfully in Android first, perhaps? Then you can be sure the creds work. I can't really provide much advice beyond that.

**Comment by jchintk** [comment]
Can the credentials be copied to Android from Linux or vice versa? 

I could setup with no problem on Android since Wireless@SGx app doesn't generate any credentials (not AFAIK).

**Comment by zerotypic** [comment]
I think the Android app does store the creds on the phone after setting things up, if you look under your list of WiFi networks you might be able to find it listed under "Wireless@SGx". Not all phones let you view the actual credentials though, some protect it. In any case, the creds you generate using wasg-register can be used in Android, you just have to enter them in manually.

**Comment by jchintk** [comment]
Hi 0typic,

As I am still trying out how to retrieve the creds from my Android phone, I could only rely on wasg-register.py for now.

oakley@oakley-HP-EliteBook-840-G1:~/Desktop/WSG$ ./wasg-register.py -r 659828xxxx 2407xxxx
OTP will be sent to mobile phone number 659828xxxx
Enter OTP to continue: 378472
Credentials:
	userid = essa-ept5umsyZ5Gec9eb9u_tekbazQ@singtel-wsg
	password = xS9a6KF^X4H81JXVkt7MTUx9w4*fvK53pkwxCkbakqw_uHWnsKUHBb3jRCYNnDVF

I was wondering if the creds generated above is correct & I just need to key into the WIFI network exactly as they are.
I'm quite certain network config is correct i.e PEAP version automatic, anonymous identity blank, MSCHAPv2.

If you know any ios or android apps to retrieve phone creds please let me know too.
 
Thanks.

**Comment by xv-ch** [comment]
Hi, any idea if the API had been updated? I'm getting a status 500 error when making both validation and retrieve requests.

**Comment by xv-ch** [comment]
Hi, any idea if the API had been updated? I'm getting a status 500 error when making both validation and retrieve requests.

**Comment by zerotypic** [comment]
Yeah I suspect there was a change. I'm not really free to look at it right now unfortunately, if somebody else wants to feel free to go ahead. Might have some time in December.

**Comment by lucidDreamss** [comment]
Did anyone manage to get this to work? Im getting the status 500 error too

**Comment by Longkho** [comment]
Yes by using yinyinmeimei code plus some minor fix

**Comment by zerotypic** [comment]
Ok, the latest merge should have fixed things, closing this.
